### ISSUE TITLE
Allow spliting terminals

### ISSUE THREAD

**Issue by JacobsonGal** [fabiospampinato/vscode-terminals#66] opened 2022-04-12 17:37 UTC
Hi!
I think it will be a great feature to add,
currently, you have all the features needed besides that one,
it could work like the splitTerminals in restoreTerminals,

I'll be happy to hear what do you think about it,
Thanks for the amazing extension! 🙏

**Comment by alextegelid** [comment] 2022-08-04 07:16
This can probably be done by programmatically calling `Terminal: Join terminals` after running the starting the terminals. I get around by manually running that command right after opening the workspace.

**Comment by JacobsonGal** [comment] 2022-08-04 18:06
@alextegelid Thanks!
Could you explain to me how can I join 8 terminals tabs into 4 joined ones?

**Comment by alextegelid** [comment] 2022-08-05 04:24
I'm not sure how you'd go about doing that. I meant that it can probably be done by the extension programatically. I have an idea and began working on a PR yesterday. However, I've never worked with the vscode API or extension development before so I'm not making any promises 😊

**Comment by teded32** [comment] 2022-08-09 01:53
Duplicate of #9

**Closed** 2022-08-19 00:28 UTC
