### ISSUE TITLE
Allow splited terminals with different settings

### ISSUE THREAD

**Issue by tamplix** [fabiospampinato/vscode-terminals#51] opened 2021-01-15 11:36 UTC
I think it will be really useful (at least for me). I use divided terminals with different purposes in a work area with 5 git repositories.
![image](https://user-images.githubusercontent.com/6863350/104722485-2bce8900-572e-11eb-98b1-2d84bf9d24c7.png)

**Comment by DanielFloris** [comment] 2021-02-11 00:29
I'd love to see this too.

**Comment by fabiospampinato** [comment] 2021-02-11 08:59
Duplicate of https://github.com/fabiospampinato/vscode-terminals/issues/9

**Closed by fabiospampinato** 2021-02-11 08:59 UTC
